name: Build and deploy backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Deploy backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'skillsync-backend-arsalan'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_CLIENTID_94E9E7D4991F4C2E9879E1FB12C98172 }}
          package: ./backend
